const data = {
  products: [
    {
      _id: '1',
      name: 'Quena',
      slug: 'quenas-quena-bambu',
      category: 'quenas',
      image: '/images/vk1.jpg', //679px x 829px
      rating: 4.5,
      numReviews: 10,
      description:
        'Quena profesional de Bambú. Disponible en diferentes afinaciones',
      price: 60,
      countInStock: 10,
    },
    {
      _id: '2',
      name: 'Juego de zampoñas en afinación Do',
      slug: 'zamponias-afinacion-do',
      category: 'zamponias',
      image: '/images/vk2.jpg',
      rating: 4.5,
      numReviews: 10,
      description:
        'Juego de zampoñas en afinación Do profesional. (Zanka, Malta e ika)',
      price: 170,
      countInStock: 0,
    },
    {
      _id: '3',
      name: 'Malta Cromática de tres filas',
      slug: 'zamponias-malta-cromatica',
      category: 'zamponias',
      image: '/images/vk3.jpg',
      rating: 4.5,
      numReviews: 10,
      description:
        'Disponible en diferentes colores de amarre (rojo, azul, negro)',
      price: 100,
      countInStock: 10,
    },
    {
      _id: '4',
      name: 'Zampoña Zanka en afinación Mi menor',
      slug: 'zamponias-zanka-mi',
      category: 'zamponias',
      image: '/images/vk4.jpg',
      rating: 4.5,
      numReviews: 10,
      description: 'Bambú de espesor grueso',
      price: 70,
      countInStock: 10,
    },
    {
      _id: '5',
      name: 'Zampoña Malta en afinación Mi menor',
      slug: 'zamponias-malta-mi',
      category: 'zamponias',
      image: '/images/vk5.jpg',
      rating: 4.5,
      numReviews: 10,
      description: 'Producto recomendado para principiantes ',
      price: 50,
      countInStock: 0,
    },
    {
      _id: '6',
      name: 'Juego de zampoñas en afinación Mi menor',
      slug: 'zamponias-juego-mi',
      category: 'zamponias',
      image: '/images/vk6.jpg',
      rating: 4.5,
      numReviews: 10,
      description: 'Zanka, Malta e Ika. Bambú de espesor grueso',
      price: 150,
      countInStock: 3,
    },
  ],
};

export default data;
